import { Button } from "@/components/ui/button";
import Link from "next/link";
import Navigation from "./_components/Navigation";
import { GrShare } from "react-icons/gr";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col w-60 h-9 mt-4 ml-14">
          <Navigation />
          <Link
            href="/dashboard/home-page"
            className="w-60 h-9 bg-[#f4f4f5] mt-1 font-medium text-black shadow-none hover:bg-[#f4f4f5]"
          >
            <Button className="bg-[#f4f4f5] w-60 font-medium text-black shadow-none hover:bg-[#f4f4f5] focus:bg-[#f4f4f5]">
              {" "}
              Home
            </Button>
          </Link>
          <Button className="bg-white mt-1 text-black shadow-none hover:bg-[#f4f4f5] focus:bg-[#f4f4f5]">
            Explore
          </Button>
          <Button className="bg-white mt-1 text-black shadow-none hover:bg-[#f4f4f5] focus:bg-[#f4f4f5]">
            View page <GrShare />{" "}
          </Button>
          <Button className="bg-white mt-1 text-black shadow-none hover:bg-[#f4f4f5] focus:bg-[#f4f4f5]">
            Account settings
          </Button>
        </div>
        {children}
      </body>
    </html>
  );
}
