import { FiCoffee } from "react-icons/fi";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <aside className="w-64 h-screen p-6">
          <h1 className="text-xl font-bold mb-6 text-black flex gap-3">
            <FiCoffee size={28} /> Buy Me Coffee
          </h1>
          <nav>
            <ul>
              <li className="mb-4">
                <a
                  href="/dashboard/home-page"
                  className="text-gray-700 hover:text-black"
                >
                  Home
                </a>
              </li>
              <li className="mb-4">
                <a
                  href="dashboard/explore"
                  className="text-gray-700 hover:text-black"
                >
                  Explore
                </a>
              </li>
              <li className="mb-4">
                <a href="#" className="text-gray-700 hover:text-black">
                  View page ↗
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-700 hover:text-black">
                  Account settings
                </a>
              </li>
            </ul>
          </nav>
        </aside>
        {children}
      </body>
    </html>
  );
}
